-- ============================================
-- cnbt-inventory - STASH MANAGER (server)
-- ============================================
--
-- Loads persistent stashes from stashes.lua, registers them with the inventory
-- system (via RegisterStash in main.lua) and exposes /depositi + net events so
-- staff can create, list and delete stashes from the in-game UI.
--
-- Persistence: when a stash is created or deleted, the whole Stashes table is
-- serialized back into stashes.lua via SaveResourceFile. That file is the
-- source of truth and is re-loaded on resource start.

local ESX = exports['es_extended']:getSharedObject()

-- ============================================
-- HELPERS
-- ============================================

local function isAdmin(src)
    local xPlayer = ESX.GetPlayerFromId(src)
    if not xPlayer then return false end
    local group = xPlayer.getGroup and xPlayer.getGroup() or nil
    if not group then return false end
    return Config.DepositAdminGroups and Config.DepositAdminGroups[group] == true
end

-- Escape a string so it is safe to embed inside a single-quoted Lua string.
local function escStr(s)
    if type(s) ~= 'string' then return '' end
    return s:gsub('\\', '\\\\'):gsub("'", "\\'"):gsub('\n', '\\n'):gsub('\r', '')
end

local function fmtNum(n)
    if type(n) ~= 'number' then return '0' end
    -- integers stay as ints, floats keep 4 decimal places
    if n == math.floor(n) then
        return tostring(math.floor(n))
    end
    return string.format('%.4f', n)
end

-- Build a Lua source file that re-declares the Stashes table. The output is
-- intentionally stable & human readable so diffs stay clean.
local function serializeStashes()
    local lines = {
        '-- ============================================',
        '-- cnbt-inventory - STASHES DATA FILE',
        '-- ============================================',
        '--',
        '-- AUTO-GENERATED by the in-game /depositi command. Do NOT edit manually.',
        '-- Any manual change will be overwritten next time a staff member creates',
        '-- or delete a stash from the deposit manager GUI.',
        '--',
        'Stashes = {}',
        '',
    }

    -- Sort keys so the file order is deterministic
    local ids = {}
    for id in pairs(Stashes or {}) do ids[#ids + 1] = id end
    table.sort(ids)

    for _, id in ipairs(ids) do
        local s = Stashes[id]
        if type(s) == 'table' then
            local pos = s.position or { x = 0, y = 0, z = 0 }
            local rot = s.rotation or { x = 0, y = 0, z = 0 }
            lines[#lines + 1] = string.format("Stashes['%s'] = {", escStr(id))
            lines[#lines + 1] = string.format("    label     = '%s',", escStr(s.label or id))
            lines[#lines + 1] = string.format('    maxWeight = %d,', math.floor(tonumber(s.maxWeight) or 50000))
            lines[#lines + 1] = string.format('    cols      = %d,', math.floor(tonumber(s.cols) or 6))
            lines[#lines + 1] = string.format('    rows      = %d,', math.floor(tonumber(s.rows) or 6))
            lines[#lines + 1] = string.format("    propModel = '%s',", escStr(s.propModel or ''))
            lines[#lines + 1] = string.format('    position  = { x = %s, y = %s, z = %s },',
                fmtNum(pos.x), fmtNum(pos.y), fmtNum(pos.z))
            lines[#lines + 1] = string.format('    rotation  = { x = %s, y = %s, z = %s },',
                fmtNum(rot.x), fmtNum(rot.y), fmtNum(rot.z))
            lines[#lines + 1] = '}'
            lines[#lines + 1] = ''
        end
    end

    return table.concat(lines, '\n')
end

local function saveStashesFile()
    local contents = serializeStashes()
    local ok = SaveResourceFile(GetCurrentResourceName(), 'stashes.lua', contents, -1)
    if not ok then
        print('[cnbt-inventory] WARNING: failed to persist stashes.lua')
    end
    return ok
end

-- Sanitize the id so it is a safe table key and filesystem-friendly
local function normalizeId(id)
    if type(id) ~= 'string' then return nil end
    id = id:gsub('[^%w_%-]', ''):lower()
    if #id == 0 then return nil end
    return id
end

-- ============================================
-- BOOT: register existing stashes
-- ============================================

-- Make sure Stashes is at least an empty table if stashes.lua is missing / bad
if type(Stashes) ~= 'table' then Stashes = {} end

CreateThread(function()
    -- Wait one tick so main.lua has defined RegisterStash
    Wait(0)
    for id, s in pairs(Stashes) do
        if RegisterStash then
            RegisterStash(id, s.cols or Config.DefaultStashCols,
                             s.rows or Config.DefaultStashRows,
                             s.maxWeight or Config.DefaultStashMaxWeight)
        end
    end
    print(('[cnbt-inventory] Loaded %d persistent stashes'):format(#(function()
        local t = {} for k in pairs(Stashes) do t[#t+1] = k end return t
    end)()))
end)

-- ============================================
-- NET EVENTS
-- ============================================

-- Client asks to open the deposit manager. Server validates admin and
-- responds with the current list + a flag that the NUI can open.
RegisterNetEvent('cnbt-inventory:stashes:openManager')
AddEventHandler('cnbt-inventory:stashes:openManager', function()
    local src = source
    if not isAdmin(src) then
        TriggerClientEvent('esx:showNotification', src, 'Permesso negato')
        return
    end

    -- Build sanitized snapshot
    local list = {}
    for id, s in pairs(Stashes) do
        list[#list + 1] = {
            id = id,
            label = s.label or id,
            maxWeight = s.maxWeight or Config.DefaultStashMaxWeight,
            cols = s.cols or Config.DefaultStashCols,
            rows = s.rows or Config.DefaultStashRows,
            propModel = s.propModel or '',
            position = s.position or { x = 0, y = 0, z = 0 },
            rotation = s.rotation or { x = 0, y = 0, z = 0 },
        }
    end
    table.sort(list, function(a, b) return a.id < b.id end)

    TriggerClientEvent('cnbt-inventory:stashes:managerData', src, list)
end)

-- Finalize a new stash after the placement editor confirms position/rotation.
-- Expected payload:
--   { id, label, maxWeight, cols, rows, propModel, position, rotation }
RegisterNetEvent('cnbt-inventory:stashes:create')
AddEventHandler('cnbt-inventory:stashes:create', function(data)
    local src = source
    if not isAdmin(src) then return end
    if type(data) ~= 'table' then return end

    local id = normalizeId(data.id)
    if not id then
        TriggerClientEvent('esx:showNotification', src, 'ID deposito non valido')
        return
    end
    if Stashes[id] then
        TriggerClientEvent('esx:showNotification', src, 'ID gia\' in uso')
        return
    end

    local entry = {
        label     = tostring(data.label or id),
        maxWeight = math.max(1, math.floor(tonumber(data.maxWeight) or Config.DefaultStashMaxWeight)),
        cols      = math.max(1, math.min(20, math.floor(tonumber(data.cols) or Config.DefaultStashCols))),
        rows      = math.max(1, math.min(20, math.floor(tonumber(data.rows) or Config.DefaultStashRows))),
        propModel = tostring(data.propModel or ''),
        position  = {
            x = tonumber(data.position and data.position.x) or 0.0,
            y = tonumber(data.position and data.position.y) or 0.0,
            z = tonumber(data.position and data.position.z) or 0.0,
        },
        rotation  = {
            x = tonumber(data.rotation and data.rotation.x) or 0.0,
            y = tonumber(data.rotation and data.rotation.y) or 0.0,
            z = tonumber(data.rotation and data.rotation.z) or 0.0,
        },
    }

    Stashes[id] = entry
    if RegisterStash then
        RegisterStash(id, entry.cols, entry.rows, entry.maxWeight)
    end
    saveStashesFile()

    -- Broadcast so every client spawns the new prop and registers ox_target
    TriggerClientEvent('cnbt-inventory:stashes:spawned', -1, id, entry)
    TriggerClientEvent('esx:showNotification', src, ('Deposito ^2%s^0 creato'):format(id))
end)

-- Delete a stash: remove from table, unregister, save file, and tell every
-- client to despawn the prop + ox_target zone.
RegisterNetEvent('cnbt-inventory:stashes:delete')
AddEventHandler('cnbt-inventory:stashes:delete', function(id)
    local src = source
    if not isAdmin(src) then return end
    id = normalizeId(id)
    if not id or not Stashes[id] then return end

    Stashes[id] = nil
    if customStashes then customStashes[id] = nil end
    saveStashesFile()

    TriggerClientEvent('cnbt-inventory:stashes:despawned', -1, id)
    TriggerClientEvent('esx:showNotification', src, ('Deposito ^1%s^0 eliminato'):format(id))
end)

-- Player walks up to a stash prop and ox_target fires "Open deposit".
-- The client tells the server which stash id it is, the server validates
-- that it exists, then routes the open through the existing inventory flow.
RegisterNetEvent('cnbt-inventory:stashes:openStash')
AddEventHandler('cnbt-inventory:stashes:openStash', function(id)
    local src = source
    id = normalizeId(id)
    if not id or not Stashes[id] then return end

    local entry = Stashes[id]
    TriggerClientEvent('cnbt-inventory:client:forceOpenExternal', src, {
        owner = id,
        invType = 'stash',
        label = entry.label or id,
    })
end)

-- Client requests the full stash list on resource start so it can spawn
-- props + ox_target zones for every persistent stash.
RegisterNetEvent('cnbt-inventory:stashes:requestAll')
AddEventHandler('cnbt-inventory:stashes:requestAll', function()
    local src = source
    local list = {}
    for id, s in pairs(Stashes) do
        list[#list + 1] = {
            id = id,
            label = s.label or id,
            propModel = s.propModel or '',
            position = s.position or { x = 0, y = 0, z = 0 },
            rotation = s.rotation or { x = 0, y = 0, z = 0 },
        }
    end
    TriggerClientEvent('cnbt-inventory:stashes:allData', src, list)
end)

print('[cnbt-inventory] Stash manager loaded')
